version: '3'

services:
  webapi:
    build: 
      context: .
      dockerfile: image/dotnet-api.dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - './src/AspApi/:/app'
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://:80/;https://.443"
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: "testpassword"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "./ssl/busbleapi.pfx"